### ISSUE TITLE
May I ask where to put an .APK file.

### ISSUE THREAD

**Issue by KH0000001** [h4ck3r0/Apktool-termux#13]
Hi, thank you for your hardworking.

Where should I store an .APK flie?

Thanks for your time!

**Comment by h4ck3r0** [comment]
Use files from playstore it provide direct access to termux directory only home not root directory

**Comment by KH0000001** [comment]
Thanks for your help!

The file was successfully recognized by storing it in directory /Termux/Apktool-termux/.

**Comment by h4ck3r0** [comment]
Don't forget to give star to my all repo it will help me
