### ISSUE TITLE
Error while cloning 

### ISSUE THREAD

**Issue by joshgadget** [h4ck3r0/Apktool-termux#19]
While cloning the tool ......it's giving errors ]
![Screenshot_20240107-110211](https://github.com/h4ck3r0/Apktool-termux/assets/147025800/9c1d4e1e-c236-48c0-a646-9f5a4340da5e)

**Comment by Biswajitboym416** [comment]
![Screenshot_2024-02-03-08-25-46-765_com termux](https://github.com/h4ck3r0/Apktool-termux/assets/55059751/6e6de8ab-8b6c-43b0-9650-6fa2e0919fe9)

Getting error when trying to compile the app

**Comment by h4ck3r0** [comment]
Don't try ot directly use proot
