### ISSUE TITLE
cannot recompile apk 

### ISSUE THREAD

**Issue by ale82to** [h4ck3r0/Apktool-termux#5]
first sorry if it's my fault having said that I vegot problem just recompiling apks.
I'm on Android 11 lineage OS.
here's an example let's say I ve decompiler an apk in Download folder (path /storage/emulated/0/Download/w)
when I try to recompile it with termux (using proot -0 since I'm on Android 11, although it makes no difference for the final error I ve got) using this command :
apktool b /storage/emulated/0/Download/w -o /storage/emulated/0/Download/3.apk

apk recompilation starts successfully but immediately stops with this error :

brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 132): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_126809485814777855077580683866559046691.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 29, --version-code, 21121120, --version-name, 6.57.6-Silver, --no-version-vectors, -F, /data/data/com.termux/files/usr/tmp/APKTOOL7736870995918880038.tmp, -e, /data/data/com.termux/files/usr/tmp/APKTOOL880027867598796953.tmp, -0, arsc, -I, /data/data/com.termux/files/home/.local/share/apktool/framework/1.apk, -S, /storage/emulated/0/Download/w/res, -M, /storage/emulated/0/Download/w/AndroidManifest.xml]

am I doing something wrong or it's a bug? thanks for the help.

**Comment by h4ck3r0** [comment]
hey bro i will personally check all this error , just give me time , stay tuned . subscribe my youtube channel i will upload solution there.

**Comment by rendiix** [comment]
you need crosscompiled custom aapt and aapt2 so that apktool can be used in termux

**Comment by Bad-Boy2p** [comment]
hey gays someone help me



[-] I: Using Apktool 2.7.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
32 bit support is deprecated. Apktool will not support 32bit on v3.0.0.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_4497777660824974012976099437039907193.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 29, --version-code, 100021, --version-name, 3.0, --no-version-vectors, -F, /data/data/com.termux/files/usr/tmp/APKTOOL15289713078579775473.tmp, -e, /data/data/com.termux/files/usr/tmp/APKTOOL9919143320129187127.tmp, -0, arsc, -I, /data/data/com.termux/files/home/.local/share/apktool/framework/1.apk, -S, /data/data/com.termux/files/usr/tmp/d20230820-12402-vs2m5g/original/res, -M, /data/data/com.termux/files/usr/tmp/d20230820-12402-vs2m5g/original/AndroidManifest.xml]
W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_4497777660824974012976099437039907193.tmp[1]: ELF�L4�L,4: inaccessible or not found
W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_4497777660824974012976099437039907193.tmp[19]: syntax error: unexpected '('
[*] Unable to rebuild apk. Trying rebuild with AAPT2..
[-] I: Using Apktool 2.7.0
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
32 bit support is deprecated. Apktool will not support 32bit on v3.0.0.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_6350375793047832234815571089210476965.tmp, compile, --dir, /data/data/com.termux/files/usr/tmp/d20230820-12402-vs2m5g/original/res, --legacy, -o, /data/data/com.termux/files/usr/tmp/d20230820-12402-vs2m5g/original/build/resources.zip]
W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_6350375793047832234815571089210476965.tmp[1]: ELF@�W4p^[4: inaccessible or not found
W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_6350375793047832234815571089210476965.tmp[5]: syntax error: unexpected '('
Error: Unable to rebuild apk with apktool

**Comment by h4ck3r0** [comment]
You can't bind all apks use small mb apk like flappy bird and don't forget every apps have their own property so may you can't bind everything

**Comment by h4ck3r0** [comment]
> hey gays someone help me
> 
> [-] I: Using Apktool 2.7.0 I: Checking whether sources has changed... I: Smaling smali folder into classes.dex... I: Checking whether resources has changed... I: Building resources... 32 bit support is deprecated. Apktool will not support 32bit on v3.0.0. brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_4497777660824974012976099437039907193.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 29, --version-code, 100021, --version-name, 3.0, --no-version-vectors, -F, /data/data/com.termux/files/usr/tmp/APKTOOL15289713078579775473.tmp, -e, /data/data/com.termux/files/usr/tmp/APKTOOL9919143320129187127.tmp, -0, arsc, -I, /data/data/com.termux/files/home/.local/share/apktool/framework/1.apk, -S, /data/data/com.termux/files/usr/tmp/d20230820-12402-vs2m5g/original/res, -M, /data/data/com.termux/files/usr/tmp/d20230820-12402-vs2m5g/original/AndroidManifest.xml] W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_4497777660824974012976099437039907193.tmp[1]: �ELF�L4�L,4: inaccessible or not found W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_4497777660824974012976099437039907193.tmp[19]: syntax error: unexpected '(' [*] Unable to rebuild apk. Trying rebuild with AAPT2.. [-] I: Using Apktool 2.7.0 I: Checking whether sources has changed... I: Checking whether resources has changed... I: Building resources... 32 bit support is deprecated. Apktool will not support 32bit on v3.0.0. brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_6350375793047832234815571089210476965.tmp, compile, --dir, /data/data/com.termux/files/usr/tmp/d20230820-12402-vs2m5g/original/res, --legacy, -o, /data/data/com.termux/files/usr/tmp/d20230820-12402-vs2m5g/original/build/resources.zip] W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_6350375793047832234815571089210476965.tmp[1]: �ELF@�W4p^[4: inaccessible or not found W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_6350375793047832234815571089210476965.tmp[5]: syntax error: unexpected '(' Error: Unable to rebuild apk with apktool

You can't bind all apks use small mb apk like flappy bird and don't forget every apps have their own property so may you can't bind everything
